version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    groups:
      dependencies:
        patterns:
          - '*'
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'Europe/Helsinki'
    cooldown:
      default-days: 2
    open-pull-requests-limit: 1
    versioning-strategy: increase
