version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'Europe/Helsinki'
    cooldown:
      default-days: 3
    versioning-strategy: increase
    labels:
      - dependabot
