version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    versioning-strategy: 'increase'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
    open-pull-requests-limit: 1
    allow:
      - dependency-type: 'direct'
