import { describe, it } from 'vitest'

import { matchFiles } from '../../lib/matchFiles.js'

const STAGED_FILES = [
  'index.ts',
  'index.js',
  'index.jsx',
  'styles.css',
  'styles.scss',
  'styles.sass',
  'styles.less',
  'data.json',
  'config.yaml',
  'README.md',
  'CHANGELOG.mdx',
  'bundle.min.js',
  'types.d.ts',
  'utils.spec.js',
  'utils.spec.ts',
  'jest.config.js',
  'vite.config.ts',
  'package.json',
  '.eslintrc',
  '.gitignore',
  '.env',
  '.env.local',
  'filea.js',
  'fileb.js',
  'filec.js',
  'test1.css',
  'test2.css',
  'test3.css',
  'src/index.js',
  'src/utils.js',
  'src/utils.ts',
  'src/components/Button.jsx',
  'src/components/Button.tsx',
  'src/components/index.ts',
  'src/.gitignore',
  'src/.env.production',
  'src/__tests__/utils.spec.js',
  'src/components/__mocks__/Button.js',
  'lib/utils.js',
  'lib/types.ts',
  'test/utils.spec.js',
  'test/helpers.ts',
  'docs/README.md',
  'config/app.json',
  'styles/main.css',
  'styles/themes/dark.scss',
  'dist/bundle.js',
  '.hidden/utils.js',
  '.hidden/lib/utils.js',
  'some/.hidden/utils.js',
  '.github/workflows/ci.yml',
  'a/b/c/types.ts',
  'packages/core/src/index.ts',
  'packages/core/package.json',
  'apps/web/src/App.tsx',
  'components/src/index.js',
  'components/lib/utils.js',
  '__tests__/utils.js',
  '__mocks__/utils.js',
  '../outside.js',
  '../styles.css',
  '../src/utils.ts',
  '../../top.js',
]

const PATTERNS = [
  [
    '*.js',
    [
      'index.js',
      'bundle.min.js',
      'utils.spec.js',
      'jest.config.js',
      'filea.js',
      'fileb.js',
      'filec.js',
      'src/index.js',
      'src/utils.js',
      'src/__tests__/utils.spec.js',
      'src/components/__mocks__/Button.js',
      'lib/utils.js',
      'test/utils.spec.js',
      'dist/bundle.js',
      '.hidden/utils.js',
      '.hidden/lib/utils.js',
      'some/.hidden/utils.js',
      'components/src/index.js',
      'components/lib/utils.js',
      '__tests__/utils.js',
      '__mocks__/utils.js',
      '../outside.js',
      '../../top.js',
    ],
  ],
  [
    '*.{js,ts}',
    [
      'index.ts',
      'index.js',
      'bundle.min.js',
      'types.d.ts',
      'utils.spec.js',
      'utils.spec.ts',
      'jest.config.js',
      'vite.config.ts',
      'filea.js',
      'fileb.js',
      'filec.js',
      'src/index.js',
      'src/utils.js',
      'src/utils.ts',
      'src/components/index.ts',
      'src/__tests__/utils.spec.js',
      'src/components/__mocks__/Button.js',
      'lib/utils.js',
      'lib/types.ts',
      'test/utils.spec.js',
      'test/helpers.ts',
      'dist/bundle.js',
      '.hidden/utils.js',
      '.hidden/lib/utils.js',
      'some/.hidden/utils.js',
      'a/b/c/types.ts',
      'packages/core/src/index.ts',
      'components/src/index.js',
      'components/lib/utils.js',
      '__tests__/utils.js',
      '__mocks__/utils.js',
      '../outside.js',
      '../src/utils.ts',
      '../../top.js',
    ],
  ],
  [
    '*.{js,ts,jsx,tsx}',
    [
      'index.ts',
      'index.js',
      'index.jsx',
      'bundle.min.js',
      'types.d.ts',
      'utils.spec.js',
      'utils.spec.ts',
      'jest.config.js',
      'vite.config.ts',
      'filea.js',
      'fileb.js',
      'filec.js',
      'src/index.js',
      'src/utils.js',
      'src/utils.ts',
      'src/components/Button.jsx',
      'src/components/Button.tsx',
      'src/components/index.ts',
      'src/__tests__/utils.spec.js',
      'src/components/__mocks__/Button.js',
      'lib/utils.js',
      'lib/types.ts',
      'test/utils.spec.js',
      'test/helpers.ts',
      'dist/bundle.js',
      '.hidden/utils.js',
      '.hidden/lib/utils.js',
      'some/.hidden/utils.js',
      'a/b/c/types.ts',
      'packages/core/src/index.ts',
      'apps/web/src/App.tsx',
      'components/src/index.js',
      'components/lib/utils.js',
      '__tests__/utils.js',
      '__mocks__/utils.js',
      '../outside.js',
      '../src/utils.ts',
      '../../top.js',
    ],
  ],
  [
    '*.{css,scss,sass,less}',
    [
      'styles.css',
      'styles.scss',
      'styles.sass',
      'styles.less',
      'test1.css',
      'test2.css',
      'test3.css',
      'styles/main.css',
      'styles/themes/dark.scss',
      '../styles.css',
    ],
  ],
  [
    '*.{json,yaml,yml}',
    [
      'data.json',
      'config.yaml',
      'package.json',
      'config/app.json',
      '.github/workflows/ci.yml',
      'packages/core/package.json',
    ],
  ],
  ['*.md(x)?', ['README.md', 'CHANGELOG.mdx', 'docs/README.md']],
  ['*.min.js', ['bundle.min.js']],
  ['*.d.ts', ['types.d.ts']],
  ['*.spec.js', ['utils.spec.js', 'src/__tests__/utils.spec.js', 'test/utils.spec.js']],
  ['*.config.js', ['jest.config.js']],
  ['README.md', ['README.md', 'docs/README.md']],
  ['package.json', ['package.json', 'packages/core/package.json']],
  ['.eslintrc', ['.eslintrc']],
  ['src/*.js', ['src/index.js', 'src/utils.js']],
  [
    'src/**/*.js',
    [
      'src/index.js',
      'src/utils.js',
      'src/__tests__/utils.spec.js',
      'src/components/__mocks__/Button.js',
    ],
  ],
  [
    'src/**/*.{js,ts,jsx,tsx}',
    [
      'src/index.js',
      'src/utils.js',
      'src/utils.ts',
      'src/components/Button.jsx',
      'src/components/Button.tsx',
      'src/components/index.ts',
      'src/__tests__/utils.spec.js',
      'src/components/__mocks__/Button.js',
    ],
  ],
  ['lib/**/*.js', ['lib/utils.js']],
  ['test/**/*.spec.js', ['test/utils.spec.js']],
  ['docs/**/*.md', ['docs/README.md']],
  ['config/**/*.json', ['config/app.json']],
  ['styles/**/*.{css,scss}', ['styles/main.css', 'styles/themes/dark.scss']],
  [
    '**/*.js',
    [
      'index.js',
      'bundle.min.js',
      'utils.spec.js',
      'jest.config.js',
      'filea.js',
      'fileb.js',
      'filec.js',
      'src/index.js',
      'src/utils.js',
      'src/__tests__/utils.spec.js',
      'src/components/__mocks__/Button.js',
      'lib/utils.js',
      'test/utils.spec.js',
      'dist/bundle.js',
      '.hidden/utils.js',
      '.hidden/lib/utils.js',
      'some/.hidden/utils.js',
      'components/src/index.js',
      'components/lib/utils.js',
      '__tests__/utils.js',
      '__mocks__/utils.js',
    ],
  ],
  [
    '**/*.{js,ts}',
    [
      'index.ts',
      'index.js',
      'bundle.min.js',
      'types.d.ts',
      'utils.spec.js',
      'utils.spec.ts',
      'jest.config.js',
      'vite.config.ts',
      'filea.js',
      'fileb.js',
      'filec.js',
      'src/index.js',
      'src/utils.js',
      'src/utils.ts',
      'src/components/index.ts',
      'src/__tests__/utils.spec.js',
      'src/components/__mocks__/Button.js',
      'lib/utils.js',
      'lib/types.ts',
      'test/utils.spec.js',
      'test/helpers.ts',
      'dist/bundle.js',
      '.hidden/utils.js',
      '.hidden/lib/utils.js',
      'some/.hidden/utils.js',
      'a/b/c/types.ts',
      'packages/core/src/index.ts',
      'components/src/index.js',
      'components/lib/utils.js',
      '__tests__/utils.js',
      '__mocks__/utils.js',
    ],
  ],
  [
    '**/*.{js,ts,jsx,tsx}',
    [
      'index.ts',
      'index.js',
      'index.jsx',
      'bundle.min.js',
      'types.d.ts',
      'utils.spec.js',
      'utils.spec.ts',
      'jest.config.js',
      'vite.config.ts',
      'filea.js',
      'fileb.js',
      'filec.js',
      'src/index.js',
      'src/utils.js',
      'src/utils.ts',
      'src/components/Button.jsx',
      'src/components/Button.tsx',
      'src/components/index.ts',
      'src/__tests__/utils.spec.js',
      'src/components/__mocks__/Button.js',
      'lib/utils.js',
      'lib/types.ts',
      'test/utils.spec.js',
      'test/helpers.ts',
      'dist/bundle.js',
      '.hidden/utils.js',
      '.hidden/lib/utils.js',
      'some/.hidden/utils.js',
      'a/b/c/types.ts',
      'packages/core/src/index.ts',
      'apps/web/src/App.tsx',
      'components/src/index.js',
      'components/lib/utils.js',
      '__tests__/utils.js',
      '__mocks__/utils.js',
    ],
  ],
  [
    '**/*.spec.{js,ts}',
    ['utils.spec.js', 'utils.spec.ts', 'src/__tests__/utils.spec.js', 'test/utils.spec.js'],
  ],
  ['**/*.config.{js,ts}', ['jest.config.js', 'vite.config.ts']],
  ['**/*.d.ts', ['types.d.ts']],
  [
    '**/index.{js,ts}',
    [
      'index.ts',
      'index.js',
      'src/index.js',
      'src/components/index.ts',
      'packages/core/src/index.ts',
      'components/src/index.js',
    ],
  ],
  ['**/package.json', ['package.json', 'packages/core/package.json']],
  ['**/.gitignore', ['.gitignore', 'src/.gitignore']],
  ['**/.env*', ['.env', '.env.local', 'src/.env.production']],
  ['*', STAGED_FILES],
  ['**', STAGED_FILES],
  ['**/*', STAGED_FILES.filter((f) => !f.startsWith('..'))],
  ['.hidden/*.js', ['.hidden/utils.js']],
  ['.hidden/**/*.js', ['.hidden/utils.js', '.hidden/lib/utils.js']],
  ['**/.hidden/*.js', ['.hidden/utils.js', 'some/.hidden/utils.js']],
  ['.github/**/*.yml', ['.github/workflows/ci.yml']],
  [
    '.*',
    ['.eslintrc', '.gitignore', '.env', '.env.local', 'src/.gitignore', 'src/.env.production'],
  ],
  ['a/b/c/*.ts', ['a/b/c/types.ts']],
  ['packages/*/src/**/*.ts', ['packages/core/src/index.ts']],
  ['apps/*/src/**/*.tsx', ['apps/web/src/App.tsx']],
  [
    '**/{src,lib}/*.js',
    [
      'src/index.js',
      'src/utils.js',
      'lib/utils.js',
      '.hidden/lib/utils.js',
      'components/src/index.js',
      'components/lib/utils.js',
    ],
  ],
  [
    '**/{__tests__,__mocks__}/**/*.js',
    [
      'src/__tests__/utils.spec.js',
      'src/components/__mocks__/Button.js',
      '__tests__/utils.js',
      '__mocks__/utils.js',
    ],
  ],
  ['file{a,b,c}.js', ['filea.js', 'fileb.js', 'filec.js']],
  ['test{1..3}.css', ['test1.css', 'test2.css', 'test3.css']],
  [
    '{src,lib,test}/**/*.ts',
    ['src/utils.ts', 'src/components/index.ts', 'lib/types.ts', 'test/helpers.ts'],
  ],
  ['../*.js', ['../outside.js']],
  ['../*.{css,js}', ['../outside.js', '../styles.css']],
  ['../src/**/*.ts', ['../src/utils.ts']],
  ['../../*.js', ['../../top.js']],
  ['unknown/*.js', []],
  ['dist/**/*.js', ['dist/bundle.js']],
]

describe('matchFiles', () => {
  it.for(PATTERNS)(
    'Should match specific files for pattern "%s"',
    ([pattern, expected], { expect }) => {
      const matchedFiles = matchFiles(
        STAGED_FILES.map((filepath) => ({ filepath, status: 'A' })),
        pattern
      )

      expect(matchedFiles.map(({ filepath }) => filepath)).toStrictEqual(expected)
    }
  )
})
