name: Default Branch Push

on:
  push:
    branches:
      - main
    # Do not run on tags
    tags-ignore:
      - '*'

permissions:
  contents: read

jobs:
  npm:
    uses: ./.github/workflows/npm.yml

  Release:
    needs: npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      packages: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
        with:
          # This is a PAT token that allows triggering of new Actions when 🦋 Changeset pushes a git tag
          token: ${{ secrets.CHANGESET_RELEASE_TOKEN }}
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # https://github.com/actions/setup-node/releases/tag/v6.3.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # https://github.com/actions/cache/releases/tag/v5.0.4
        id: cache-node_modules
        with:
          path: node_modules
          key: node-modules-ubuntu-latest-${{ hashFiles('package-lock.json') }}
      - name: Create Release Pull Request
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # https://github.com/changesets/action/releases/tag/v1.7.0
        with:
          title: '🦋 Changeset release'
          version: npm run version
          publish: npm run tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: '0' # disabled because pre-push hook checks for changesets which have now been removed
