name: Default Branch Push

on:
  push:
    branches:
      - main
    # Do not run on tags
    tags-ignore:
      - '*'

permissions:
  contents: write
  issues: read
  packages: write
  pull-requests: write
  id-token: write

jobs:
  npm:
    uses: ./.github/workflows/npm.yml

  Release:
    needs: npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This is a PAT token that allows triggering of new Actions when 🦋 Changeset pushes a git tag
          token: ${{ secrets.CHANGESET_RELEASE_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: actions/cache@v4
        id: cache-node_modules
        with:
          path: node_modules
          key: node-modules-ubuntu-latest-${{ hashFiles('package-lock.json') }}
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: '🦋 Changeset release'
          version: npm run version
          publish: npm run tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: '0' # disabled because pre-push hook checks for changesets which have now been removed
