name: Test & Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-node-range:
    name: Test Node.js version range
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v4
        id: cache-node_modules
        with:
          path: node_modules
          key: ubuntu-latest-20-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ubuntu-latest-20-${{ hashFiles('**/package-lock.json') }}
      - if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci
      - run: node ./scripts/test-node-range.js
