name: Security Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' # 00:00 on Monday.

permissions:
  contents: read
  security-events: write

jobs:
  CodeQL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
      - uses: github/codeql-action/init@38697555549f1db7851b81482ff19f1fa5c4fedc # https://github.com/github/codeql-action/releases/tag/v4.34.1
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@38697555549f1db7851b81482ff19f1fa5c4fedc # https://github.com/github/codeql-action/releases/tag/v4.34.1

  npm:
    uses: ./.github/workflows/npm.yml

  npm-audit:
    runs-on: ubuntu-latest
    needs: npm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
      - run: npm audit --include prod --audit-level high
